import { BidMonthData, DealConversionStats, MetricCardData, QuoteItem, RfqComparisonItem, TimeRange } from './types';

export const METRIC_CARDS_BY_RANGE: Record<TimeRange, MetricCardData[]> = {
  '30d': [
    {
      id: 'margin-saved',
      title: 'Margin saved',
      value: '$13,700',
      trend: '+18% vs. last month',
      trendColor: 'orange',
      trendDirection: 'up',
      iconName: 'dollar',
    },
    {
      id: 'time-saved',
      title: 'Time saved',
      value: '84h',
      trend: '+12h vs. last month',
      trendColor: 'green',
      trendDirection: 'up',
      iconName: 'clock',
    },
    {
      id: 'open-bids',
      title: 'Open bids',
      value: '12',
      secondaryText: '$495,000',
      iconName: 'file-text',
    },
    {
      id: 'revisions-analyzed',
      title: 'Revisions analyzed',
      value: '156',
      trend: '+24 this week',
      trendColor: 'orange',
      trendDirection: 'up',
      iconName: 'file-check',
    },
  ],
  'quarter': [
    {
      id: 'margin-saved',
      title: 'Margin saved',
      value: '$48,250',
      trend: '+22% vs. prior Qtr',
      trendColor: 'orange',
      trendDirection: 'up',
      iconName: 'dollar',
    },
    {
      id: 'time-saved',
      title: 'Time saved',
      value: '260h',
      trend: '+38h vs. prior Qtr',
      trendColor: 'green',
      trendDirection: 'up',
      iconName: 'clock',
    },
    {
      id: 'open-bids',
      title: 'Open bids',
      value: '34',
      secondaryText: '$1,420,000',
      iconName: 'file-text',
    },
    {
      id: 'revisions-analyzed',
      title: 'Revisions analyzed',
      value: '492',
      trend: '+68 this month',
      trendColor: 'orange',
      trendDirection: 'up',
      iconName: 'file-check',
    },
  ],
  'year': [
    {
      id: 'margin-saved',
      title: 'Margin saved',
      value: '$184,900',
      trend: '+31% YoY',
      trendColor: 'orange',
      trendDirection: 'up',
      iconName: 'dollar',
    },
    {
      id: 'time-saved',
      title: 'Time saved',
      value: '1,040h',
      trend: '+142h YoY',
      trendColor: 'green',
      trendDirection: 'up',
      iconName: 'clock',
    },
    {
      id: 'open-bids',
      title: 'Open bids',
      value: '128',
      secondaryText: '$5,820,000',
      iconName: 'file-text',
    },
    {
      id: 'revisions-analyzed',
      title: 'Revisions analyzed',
      value: '1,840',
      trend: '+19% annualized',
      trendColor: 'orange',
      trendDirection: 'up',
      iconName: 'file-check',
    },
  ],
};

// 6 months of bid cumulative data: May (190k), Jun (280k), Jul (330k), Aug (300k), Sep (440k), Oct (500k)
export const BIDS_IN_MARKET_DATA: BidMonthData[] = [
  {
    month: 'May',
    value: 190000,
    displayValue: '$190k',
    bidCount: 8,
    avgMargin: '21.4%',
  },
  {
    month: 'Jun',
    value: 280000,
    displayValue: '$280k',
    bidCount: 11,
    avgMargin: '23.1%',
  },
  {
    month: 'Jul',
    value: 330000,
    displayValue: '$330k',
    bidCount: 14,
    avgMargin: '24.8%',
  },
  {
    month: 'Aug',
    value: 300000,
    displayValue: '$300k',
    bidCount: 10,
    avgMargin: '22.9%',
  },
  {
    month: 'Sep',
    value: 440000,
    displayValue: '$440k',
    bidCount: 16,
    avgMargin: '26.2%',
  },
  {
    month: 'Oct',
    value: 500000,
    displayValue: '$500k',
    bidCount: 19,
    avgMargin: '27.5%',
  },
];

export const DEALS_CONVERSION_STATS: DealConversionStats = {
  wonJobs: 38,
  avgDurationDays: 17,
  closeRate: 24, // 24%
  quarterlyGoal: 50,
  currentCompleted: 38,
};

export const RECENT_QUOTES_LIST: QuoteItem[] = [
  {
    id: 'Q-2026-891',
    title: 'Aerospace Turbine Flanges (Rev C)',
    customer: 'Apex Dynamics Corp',
    value: 142000,
    status: 'Won',
    date: 'Oct 14, 2026',
    margin: '28.4%',
    revision: 'Rev C.2',
  },
  {
    id: 'Q-2026-894',
    title: 'Precision Hydraulic Manifold Blocks',
    customer: 'Vanguard Industrial',
    value: 88500,
    status: 'Submitted',
    date: 'Oct 16, 2026',
    margin: '25.1%',
    revision: 'Rev B',
  },
  {
    id: 'Q-2026-897',
    title: 'Titanium Medical Impeller Housings',
    customer: 'BioNexus Instruments',
    value: 164000,
    status: 'Under Review',
    date: 'Oct 18, 2026',
    margin: '31.2%',
    revision: 'Rev D.1',
  },
  {
    id: 'Q-2026-902',
    title: 'Structural Bracket Assembly Batch',
    customer: 'Cobalt Energy Systems',
    value: 62000,
    status: 'Draft',
    date: 'Oct 20, 2026',
    margin: '22.0%',
    revision: 'Rev A',
  },
  {
    id: 'Q-2026-905',
    title: 'Cryogenic Valve Valve Sleeves',
    customer: 'AeroFluidic Solutions',
    value: 125000,
    status: 'Won',
    date: 'Oct 21, 2026',
    margin: '27.8%',
    revision: 'Rev C',
  },
];

export const RFQ_COMPARISONS: RfqComparisonItem[] = [
  {
    id: 'RFQ-7741',
    rfqNumber: 'RFQ-7741-B',
    client: 'Apex Dynamics',
    partDescription: 'Turbine Casing High-Tolerance Stator',
    internalEstimate: 118000,
    quotedPrice: 142000,
    deltaPercent: '+20.3%',
    leadTime: '4 weeks',
    riskScore: 'Low',
  },
  {
    id: 'RFQ-7744',
    rfqNumber: 'RFQ-7744-A',
    client: 'Vanguard Ind.',
    partDescription: 'CNC Milled Anodized Baseplate 7075-T6',
    internalEstimate: 69000,
    quotedPrice: 88500,
    deltaPercent: '+28.2%',
    leadTime: '3 weeks',
    riskScore: 'Low',
  },
  {
    id: 'RFQ-7750',
    rfqNumber: 'RFQ-7750-C',
    client: 'BioNexus',
    partDescription: 'Laser Sintered Ti-6Al-4V Medical Casing',
    internalEstimate: 125000,
    quotedPrice: 164000,
    deltaPercent: '+31.2%',
    leadTime: '6 weeks',
    riskScore: 'Medium',
  },
  {
    id: 'RFQ-7752',
    rfqNumber: 'RFQ-7752-F',
    client: 'Nordic Marine',
    partDescription: 'Inconel 625 Sealing Ring Gaskets',
    internalEstimate: 74000,
    quotedPrice: 91000,
    deltaPercent: '+23.0%',
    leadTime: '5 weeks',
    riskScore: 'Low',
  },
];

export const REVISION_CHECK_DATA = [
  {
    id: 'REV-01',
    document: 'DWG-902-AERO-TURBINE.pdf',
    part: 'Turbine Flange Assembly',
    detectedDelta: 'Hole diameter changed 12.5mm -> 12.0mm; Tol ±0.02',
    costImpact: '+$1,450 machining cycle time',
    analyzedAt: '12 mins ago',
    status: 'Flagged for Quoting',
  },
  {
    id: 'REV-02',
    document: 'SPEC-882-MANIFOLD.step',
    part: 'Hydraulic Valve Block',
    detectedDelta: 'Surface finish spec upgraded to Ra 0.4 μm',
    costImpact: '+$820 honing operation',
    analyzedAt: '45 mins ago',
    status: 'Approved',
  },
  {
    id: 'REV-03',
    document: 'BOM-441-ENERGY-BRACKET.xlsx',
    part: 'Structural Fastener Array',
    detectedDelta: 'Hardware alloy switched to 316L SS',
    costImpact: '+$340 material delta',
    analyzedAt: '2 hours ago',
    status: 'Under Review',
  },
];

export const RECENT_NOTIFICATIONS = [
  {
    id: 'notif-1',
    title: 'Revision discrepancy identified',
    description: 'DWG-902-AERO: +$1,450 margin impact flagged automatically.',
    time: '12m ago',
    unread: true,
  },
  {
    id: 'notif-2',
    title: 'Quote Q-2026-891 Won',
    description: 'Apex Dynamics accepted bid at $142,000 (28.4% margin).',
    time: '2h ago',
    unread: true,
  },
  {
    id: 'notif-3',
    title: 'RFQ-7750 Target review deadline',
    description: 'Client requested expediting response within 24 hours.',
    time: '5h ago',
    unread: false,
  },
];
